name: pull-request-gate

on:
  pull_request:
    branches: [ '*' ]

env:
  BUILD_VERSION: 0.0.0.${{github.run_number}}
  SLN_PATH: src/CleanAll.sln

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore $SLN_PATH

    - name: Build
      run: dotnet build $SLN_PATH 
           -c Release 
           --no-restore 
           -p:Version=$BUILD_VERSION

    - name: Upload ShellRunner Build Artifacts
      uses: actions/upload-artifact@v4.6.1
      with:
        name: BuildArtifacts
        path: ./**/bin/Release/**/*
