name: .NET

on:
  push:
    branches: [ "stable" ]

env:
  BUILD_VERSION: 0.0.2.${{github.run_number}}
  SLN_PATH: src/CleanAll.sln
  PROJECT_PATH: src/CleanAll/CleanAll.csproj

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 #v5.2.0
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore $SLN_PATH

    - name: Build
      run: dotnet build $SLN_PATH 
           -c Release 
           --no-restore 
           -p:Version=$BUILD_VERSION
           
    - name: Pack-Alpha
      run: dotnet pack $PROJECT_PATH
           -c Release 
           --no-restore 
           --no-build
           -p:PackageVersion=$BUILD_VERSION-alpha
           -o alpha-packages

    - name: Pack-Release
      run: dotnet pack $PROJECT_PATH
           -c Release 
           --no-restore 
           --no-build
           -p:PackageVersion=$BUILD_VERSION
           -o packages

    - name: Upload PreRelease Artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: PreReleaseArtifacts
        path: alpha-packages/*.nupkg
        if-no-files-found: error
           
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: ReleaseArtifacts
        path: packages/*.nupkg
        if-no-files-found: error

  pre-release:
    needs: build
    name: Deploy Pre-Release Nugets
    environment: 
      name: Integration
    runs-on: ubuntu-22.04
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
      with:
        name: PreReleaseArtifacts    
    
    - name: nuget-logon
      uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 #v1.2.0
      id: login
        
    - name: Push Pre-Release Nuget
      run: dotnet nuget push ./alpha-packages/*-alpha.nupkg 
           --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

  release:
    needs: build
    name: Deploy Release Nugets
    environment: 
      name: Production
    runs-on: ubuntu-22.04
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
      with:
        name: ReleaseArtifacts    
           
    - name: nuget-logon
      uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 #v1.2.0
      id: login
        
    - name: Push ShellRunner Pre-Release Nuget
      run: dotnet nuget push ./packages/*.nupkg 
           --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
